import 'package:wild/features/settings/stores/api_host_store.dart';
import 'package:wild/features/settings/stores/reader_background_store.dart';
import 'package:wild/features/settings/stores/volume_control_store.dart';
import 'package:wild/features/auth/stores/auth_store.dart';
import 'package:wild/features/home/stores/bookshelf_store.dart';
import 'package:wild/features/novel/stores/bottom_bar_height_store.dart';
import 'package:wild/features/novel/stores/font_size_store.dart';
import 'package:wild/features/novel/stores/left_padding_store.dart';
import 'package:wild/features/novel/stores/line_height_store.dart';
import 'package:wild/features/novel/stores/paragraph_spacing_store.dart';
import 'package:wild/features/novel/stores/reader_type_store.dart';
import 'package:wild/features/novel/stores/right_padding_store.dart';
import 'package:wild/features/novel/stores/theme_store.dart';
import 'package:wild/features/novel/stores/top_bar_height_store.dart';
import 'package:wild/features/app/stores/update_store.dart';

final auth = AuthStore();
final bookshelf = BookshelfStore();
final theme = ThemeStore();
final fontSize = FontSizeStore();
final lineHeight = LineHeightStore();
final paragraphSpacing = ParagraphSpacingStore();
final topBarHeight = TopBarHeightStore();
final bottomBarHeight = BottomBarHeightStore();
final leftPadding = LeftPaddingStore();
final rightPadding = RightPaddingStore();
final update = UpdateStore();
final readerType = ReaderTypeStore();
final apiHost = ApiHostStore();
final readerBackground = ReaderBackgroundStore();
final volumeControl = VolumeControlStore();
