// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class BookshelfItem {
  final Novel novel;
  final String lastRead;

  const BookshelfItem({required this.novel, required this.lastRead});

  @override
  int get hashCode => novel.hashCode ^ lastRead.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BookshelfItem &&
          runtimeType == other.runtimeType &&
          novel == other.novel &&
          lastRead == other.lastRead;
}

class HomeBlock {
  final String title;
  final List<NovelCover> list;

  const HomeBlock({required this.title, required this.list});

  @override
  int get hashCode => title.hashCode ^ list.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HomeBlock &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          list == other.list;
}

class Novel {
  final String id;
  final String title;
  final String author;
  final String coverUrl;
  final String lastChapter;
  final List<String> tags;

  const Novel({
    required this.id,
    required this.title,
    required this.author,
    required this.coverUrl,
    required this.lastChapter,
    required this.tags,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      author.hashCode ^
      coverUrl.hashCode ^
      lastChapter.hashCode ^
      tags.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Novel &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          author == other.author &&
          coverUrl == other.coverUrl &&
          lastChapter == other.lastChapter &&
          tags == other.tags;
}

class NovelCover {
  final String title;
  final String img;
  final String detailUrl;
  final String aid;

  const NovelCover({
    required this.title,
    required this.img,
    required this.detailUrl,
    required this.aid,
  });

  @override
  int get hashCode =>
      title.hashCode ^ img.hashCode ^ detailUrl.hashCode ^ aid.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NovelCover &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          img == other.img &&
          detailUrl == other.detailUrl &&
          aid == other.aid;
}

class UserDetail {
  final String username;
  final String userId;
  final String nickname;
  final String level;
  final String title;
  final String sex;
  final String email;
  final String qq;
  final String msn;
  final String web;
  final String registerDate;
  final String contributePoint;
  final String experienceValue;
  final String holdingPoints;
  final String quantityOfFriends;
  final String quantityOfMail;
  final String quantityOfCollection;
  final String quantityOfRecommendDaily;
  final String personalizedSignature;
  final String personalizedDescription;

  const UserDetail({
    required this.username,
    required this.userId,
    required this.nickname,
    required this.level,
    required this.title,
    required this.sex,
    required this.email,
    required this.qq,
    required this.msn,
    required this.web,
    required this.registerDate,
    required this.contributePoint,
    required this.experienceValue,
    required this.holdingPoints,
    required this.quantityOfFriends,
    required this.quantityOfMail,
    required this.quantityOfCollection,
    required this.quantityOfRecommendDaily,
    required this.personalizedSignature,
    required this.personalizedDescription,
  });

  @override
  int get hashCode =>
      username.hashCode ^
      userId.hashCode ^
      nickname.hashCode ^
      level.hashCode ^
      title.hashCode ^
      sex.hashCode ^
      email.hashCode ^
      qq.hashCode ^
      msn.hashCode ^
      web.hashCode ^
      registerDate.hashCode ^
      contributePoint.hashCode ^
      experienceValue.hashCode ^
      holdingPoints.hashCode ^
      quantityOfFriends.hashCode ^
      quantityOfMail.hashCode ^
      quantityOfCollection.hashCode ^
      quantityOfRecommendDaily.hashCode ^
      personalizedSignature.hashCode ^
      personalizedDescription.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UserDetail &&
          runtimeType == other.runtimeType &&
          username == other.username &&
          userId == other.userId &&
          nickname == other.nickname &&
          level == other.level &&
          title == other.title &&
          sex == other.sex &&
          email == other.email &&
          qq == other.qq &&
          msn == other.msn &&
          web == other.web &&
          registerDate == other.registerDate &&
          contributePoint == other.contributePoint &&
          experienceValue == other.experienceValue &&
          holdingPoints == other.holdingPoints &&
          quantityOfFriends == other.quantityOfFriends &&
          quantityOfMail == other.quantityOfMail &&
          quantityOfCollection == other.quantityOfCollection &&
          quantityOfRecommendDaily == other.quantityOfRecommendDaily &&
          personalizedSignature == other.personalizedSignature &&
          personalizedDescription == other.personalizedDescription;
}
