// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class BookshelfItem {
  final Novel novel;
  final String lastRead;

  const BookshelfItem({required this.novel, required this.lastRead});

  @override
  int get hashCode => novel.hashCode ^ lastRead.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BookshelfItem &&
          runtimeType == other.runtimeType &&
          novel == other.novel &&
          lastRead == other.lastRead;
}

class Novel {
  final String id;
  final String title;
  final String author;
  final String coverUrl;
  final String lastChapter;
  final List<String> tags;

  const Novel({
    required this.id,
    required this.title,
    required this.author,
    required this.coverUrl,
    required this.lastChapter,
    required this.tags,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      author.hashCode ^
      coverUrl.hashCode ^
      lastChapter.hashCode ^
      tags.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Novel &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          author == other.author &&
          coverUrl == other.coverUrl &&
          lastChapter == other.lastChapter &&
          tags == other.tags;
}
