// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../wenku8/models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<void> wenku8Login({
  required String username,
  required String password,
}) => RustLib.instance.api.crateApiWenku8Wenku8Login(
  username: username,
  password: password,
);

Future<List<BookshelfItem>> wenku8GetBookshelf() =>
    RustLib.instance.api.crateApiWenku8Wenku8GetBookshelf();
