// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../wenku8/models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<void> wenku8Login({
  required String username,
  required String password,
  required String checkcode,
}) => RustLib.instance.api.crateApiWenku8Wenku8Login(
  username: username,
  password: password,
  checkcode: checkcode,
);

Future<List<BookshelfItem>> wenku8GetBookshelf() =>
    RustLib.instance.api.crateApiWenku8Wenku8GetBookshelf();

Future<bool> preLoginState() =>
    RustLib.instance.api.crateApiWenku8PreLoginState();

Future<Uint8List> downloadCheckcode() =>
    RustLib.instance.api.crateApiWenku8DownloadCheckcode();

Future<UserDetail> userDetail() =>
    RustLib.instance.api.crateApiWenku8UserDetail();
